//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace verifyANDtransform.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Iverify")]
    public interface Iverify {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iverify/validateXML", ReplyAction="http://tempuri.org/Iverify/validateXMLResponse")]
        string validateXML(string xmldocpath, string xsddocpath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iverify/validateXML", ReplyAction="http://tempuri.org/Iverify/validateXMLResponse")]
        System.Threading.Tasks.Task<string> validateXMLAsync(string xmldocpath, string xsddocpath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IverifyChannel : verifyANDtransform.ServiceReference2.Iverify, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IverifyClient : System.ServiceModel.ClientBase<verifyANDtransform.ServiceReference2.Iverify>, verifyANDtransform.ServiceReference2.Iverify {
        
        public IverifyClient() {
        }
        
        public IverifyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IverifyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IverifyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IverifyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validateXML(string xmldocpath, string xsddocpath) {
            return base.Channel.validateXML(xmldocpath, xsddocpath);
        }
        
        public System.Threading.Tasks.Task<string> validateXMLAsync(string xmldocpath, string xsddocpath) {
            return base.Channel.validateXMLAsync(xmldocpath, xsddocpath);
        }
    }
}
