//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_TryIt_.validateservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="validateservice.IValidateXML")]
    public interface IValidateXML {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidateXML/validate", ReplyAction="http://tempuri.org/IValidateXML/validateResponse")]
        string validate(string xml1, string xsd1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidateXML/validate", ReplyAction="http://tempuri.org/IValidateXML/validateResponse")]
        System.Threading.Tasks.Task<string> validateAsync(string xml1, string xsd1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidateXMLChannel : GUI_TryIt_.validateservice.IValidateXML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateXMLClient : System.ServiceModel.ClientBase<GUI_TryIt_.validateservice.IValidateXML>, GUI_TryIt_.validateservice.IValidateXML {
        
        public ValidateXMLClient() {
        }
        
        public ValidateXMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateXMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateXMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateXMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validate(string xml1, string xsd1) {
            return base.Channel.validate(xml1, xsd1);
        }
        
        public System.Threading.Tasks.Task<string> validateAsync(string xml1, string xsd1) {
            return base.Channel.validateAsync(xml1, xsd1);
        }
    }
}
