//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_TryIt_.transformservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="transformservice.ITransformXML")]
    public interface ITransformXML {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransformXML/transform", ReplyAction="http://tempuri.org/ITransformXML/transformResponse")]
        string transform(string xml1, string xsl1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransformXML/transform", ReplyAction="http://tempuri.org/ITransformXML/transformResponse")]
        System.Threading.Tasks.Task<string> transformAsync(string xml1, string xsl1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransformXMLChannel : GUI_TryIt_.transformservice.ITransformXML, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransformXMLClient : System.ServiceModel.ClientBase<GUI_TryIt_.transformservice.ITransformXML>, GUI_TryIt_.transformservice.ITransformXML {
        
        public TransformXMLClient() {
        }
        
        public TransformXMLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransformXMLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransformXMLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransformXMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string transform(string xml1, string xsl1) {
            return base.Channel.transform(xml1, xsl1);
        }
        
        public System.Threading.Tasks.Task<string> transformAsync(string xml1, string xsl1) {
            return base.Channel.transformAsync(xml1, xsl1);
        }
    }
}
