//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncryptionDecryptionCLient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Encryption", ReplyAction="http://tempuri.org/IService2/EncryptionResponse")]
        string Encryption(string plain_text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Encryption", ReplyAction="http://tempuri.org/IService2/EncryptionResponse")]
        System.Threading.Tasks.Task<string> EncryptionAsync(string plain_text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Decryption", ReplyAction="http://tempuri.org/IService2/DecryptionResponse")]
        string Decryption(string encypted_text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Decryption", ReplyAction="http://tempuri.org/IService2/DecryptionResponse")]
        System.Threading.Tasks.Task<string> DecryptionAsync(string encypted_text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : EncryptionDecryptionCLient.ServiceReference1.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<EncryptionDecryptionCLient.ServiceReference1.IService2>, EncryptionDecryptionCLient.ServiceReference1.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Encryption(string plain_text) {
            return base.Channel.Encryption(plain_text);
        }
        
        public System.Threading.Tasks.Task<string> EncryptionAsync(string plain_text) {
            return base.Channel.EncryptionAsync(plain_text);
        }
        
        public string Decryption(string encypted_text) {
            return base.Channel.Decryption(encypted_text);
        }
        
        public System.Threading.Tasks.Task<string> DecryptionAsync(string encypted_text) {
            return base.Channel.DecryptionAsync(encypted_text);
        }
    }
}
